/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TampilanMenu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class formLab extends javax.swing.JFrame {
    private void tampilkandata(){
        DefaultTableModel x = new DefaultTableModel();
        x.addColumn("KODE LAB");
        x.addColumn("NAMA LAB");
        x.addColumn("RUANG LAB");
        x.addColumn("KAPASITAS");
        
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String strSelect = "select * from lab";
            
            ResultSet rset=stmt.executeQuery(strSelect);
            
            while(rset.next()){
                x.addRow(new Object[] {rset.getString(1),rset.getString(2),rset.getString(3),rset.getString(4)});
            }
            tbllab.setModel(x);
        }catch(SQLException ex){
            
        }
    }
    /**
     * Creates new form formLab
     */
    public formLab() {
        initComponents();
        tampilkandata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfkodelab = new javax.swing.JTextField();
        tfnamalab = new javax.swing.JTextField();
        tfruang = new javax.swing.JTextField();
        tfkapasitas = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllab = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        tfpesan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LABKOM ITERA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("LABKOM ITERA"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("KODE LAB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 73, -1, -1));

        jLabel2.setText("RUANG LAB");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 152, -1, -1));

        jLabel3.setText("NAMA LAB");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 114, -1, -1));

        jLabel4.setText("KAPASITAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 187, -1, -1));

        tfkodelab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkodelabActionPerformed(evt);
            }
        });
        getContentPane().add(tfkodelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 70, 244, -1));

        tfnamalab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamalabActionPerformed(evt);
            }
        });
        getContentPane().add(tfnamalab, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 108, 244, -1));

        tfruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfruangActionPerformed(evt);
            }
        });
        getContentPane().add(tfruang, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 146, 244, -1));

        tfkapasitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkapasitasActionPerformed(evt);
            }
        });
        getContentPane().add(tfkapasitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 184, 244, -1));

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 325, -1, -1));

        tbllab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE LAB", "NAMA LAB", "RUANG LAB", "KAPASITAS"
            }
        ));
        tbllab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbllab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 70, 571, 278));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 258, -1, -1));

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 258, -1, -1));

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 325, -1, -1));
        getContentPane().add(tfpesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 393, 340, 80));

        jLabel5.setText("MODIFIKASI DATA LAB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 11, -1, 41));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfkodelabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkodelabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkodelabActionPerformed

    private void tfnamalabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamalabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamalabActionPerformed

    private void tfkapasitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkapasitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkapasitasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Lab x = new Lab();
        x.setVisible(true); //menampilkan form yang dituju
        this.setVisible(false); //menghilangkan form saat ini
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfruangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfruangActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbllab.getModel();
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String update = "update lab set kode_lab='"+tfkodelab.getText()+"',nama_lab='"+tfnamalab.getText()+"',nama_ruang='"+tfruang.getText()+
                    "',kapasitas="+tfkapasitas.getText()+" where kode_lab='"+model.getValueAt(tbllab.getSelectedRow(), 0).toString()+"'";
            stmt.executeUpdate(update);
            tfpesan.setText("update data berhasil");
            tampilkandata();
        }catch (SQLException ex) {
            tfpesan.setText("gagal update data");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String insert = "insert into lab values ('"+tfkodelab.getText()+"','"+tfnamalab.getText()+"','"+tfruang.getText()+"',"+
                    tfkapasitas.getText()+")";
            stmt.executeUpdate(insert);
            tfpesan.setText("tambah data berhasil");
            tampilkandata();        
            
        } catch (SQLException ex) {
            tfpesan.setText("gagal tambah data");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String delete = "delete from lab where kode_lab = '"+tfkodelab.getText()+"'";
            stmt.executeUpdate(delete);
            tfpesan.setText("hapus data berhasil");
            tampilkandata();
        }catch (SQLException ex) {
            tfpesan.setText("gagal hapus data");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tbllabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllabMouseClicked
       DefaultTableModel model = (DefaultTableModel) tbllab.getModel();
       tfkodelab.setText(model.getValueAt(tbllab.getSelectedRow(), 0).toString());
       tfnamalab.setText(model.getValueAt(tbllab.getSelectedRow(), 1).toString());
       tfruang.setText(model.getValueAt(tbllab.getSelectedRow(), 2).toString());
       tfkapasitas.setText(model.getValueAt(tbllab.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tbllabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllab;
    private javax.swing.JTextField tfkapasitas;
    private javax.swing.JTextField tfkodelab;
    private javax.swing.JTextField tfnamalab;
    private javax.swing.JTextField tfpesan;
    private javax.swing.JTextField tfruang;
    // End of variables declaration//GEN-END:variables
}
