/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TampilanMenu;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class menuJadwal extends javax.swing.JFrame {
  private void kosongft(){
        tfid.setText(null);
        tfprodi.setText(null);
        tfmatkul.setText(null);
        cmbhari.setSelectedIndex(0);
        tfjam.setText(null);
        tfkodelab.setText(null);
    }
    private void tampilkandata(){
        DefaultTableModel x = new DefaultTableModel();
        x.addColumn("id jadwal");
        x.addColumn("program studi");
        x.addColumn("mata kuliah");
        x.addColumn("hari");
        x.addColumn("jam");
        x.addColumn("kode lab");
        
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String strSelect = "select * from jadwal";
            
            ResultSet rset=stmt.executeQuery(strSelect);
            
            while(rset.next()){
                x.addRow(new Object[] {rset.getString(1),rset.getString(2),rset.getString(3),rset.getString(5),rset.getString(6),rset.getString(4)});
            }
            tbljadwal.setModel(x);
        }catch(SQLException ex){
            
        }
    }
    /**
     * Creates new form login
     */
    public menuJadwal() {
        initComponents();
        tampilkandata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbljadwal = new javax.swing.JTable();
        jLidjadwal = new javax.swing.JLabel();
        jlmatkul = new javax.swing.JLabel();
        jlprodi = new javax.swing.JLabel();
        jljam = new javax.swing.JLabel();
        jlhari = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        tfprodi = new javax.swing.JTextField();
        tfmatkul = new javax.swing.JTextField();
        tfjam = new javax.swing.JTextField();
        cmbhari = new javax.swing.JComboBox();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        tfpesan = new javax.swing.JTextField();
        jlkodealab = new javax.swing.JLabel();
        tfkodelab = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbljadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id jadwal", "program studi", "mata kuliah", "hari", "jam", "kode lab"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbljadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbljadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbljadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbljadwal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1001, 151));

        jLidjadwal.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLidjadwal.setText("id jadwal");
        getContentPane().add(jLidjadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 24));

        jlmatkul.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jlmatkul.setText("mata kuliah");
        getContentPane().add(jlmatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 112, 69, 24));

        jlprodi.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jlprodi.setText("program studi");
        getContentPane().add(jlprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 75, 103, 24));

        jljam.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jljam.setText("jam");
        getContentPane().add(jljam, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 177, 69, 24));

        jlhari.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jlhari.setText("hari");
        getContentPane().add(jlhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 147, 69, 24));

        tfid.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 41, 349, 22));

        tfprodi.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        getContentPane().add(tfprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 75, 349, 26));

        tfmatkul.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        getContentPane().add(tfmatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 114, 349, -1));

        tfjam.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        getContentPane().add(tfjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 179, 349, -1));

        cmbhari.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        cmbhari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "senin", "selasa", "rabu", "kamis", "jumat", "sabtu", "minggu" }));
        getContentPane().add(cmbhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 149, 349, -1));

        btnadd.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnadd.setText("add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 242, -1, -1));

        btndelete.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 242, -1, -1));

        btnupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 242, -1, -1));

        btncancel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btncancel.setText("cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 242, 90, -1));

        tfpesan.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        tfpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpesanActionPerformed(evt);
            }
        });
        getContentPane().add(tfpesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 278, 518, 64));

        jlkodealab.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jlkodealab.setText("kode lab");
        getContentPane().add(jlkodealab, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 207, 69, 24));

        tfkodelab.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        getContentPane().add(tfkodelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 209, 349, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("MODIFIKASI DATA JADWAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 410, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/graphic-background-png-5.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbljadwal.getModel();
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String update = "update jadwal set id_jadwal="+tfid.getText()+",prodi='"+tfprodi.getText()+"',mata_kuliah='"+tfmatkul.getText()+
                    "',kode_lab='"+tfkodelab.getText()+"',hari='"+cmbhari.getSelectedItem()+"',jam='"+tfjam.getText()+"' where id_jadwal = "+model.getValueAt(tbljadwal.getSelectedRow(), 0);
            stmt.executeUpdate(update);
            tfpesan.setText("update data berhasil");
            tampilkandata();
            kosongft();
        }catch (SQLException ex) {
            tfpesan.setText("gagal update data");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String insert = "insert into jadwal values ("+tfid.getText()+",'"+tfprodi.getText()+"','"+tfmatkul.getText()+"','"+
                    tfkodelab.getText().toUpperCase()+"','"+cmbhari.getSelectedItem()+"','"+tfjam.getText()+"')";
            stmt.executeUpdate(insert);
            tfpesan.setText("tambah data berhasil");
            tampilkandata();        
            kosongft();
        } catch (SQLException ex) {
            tfpesan.setText("gagal tambah data");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try(
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/labkom_itera1",
                    "root",
                    "");
                Statement stmt = conn.createStatement();
        ){
            String delete = "delete from jadwal where id_jadwal = '"+tfid.getText()+"'";
            stmt.executeUpdate(delete);
            tfpesan.setText("hapus data berhasil");
            tampilkandata();
            kosongft();
        }catch (SQLException ex) {
            tfpesan.setText("gagal hapus data");
        }
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        Jadwal x = new Jadwal();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void tfpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpesanActionPerformed

    private void tbljadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbljadwalMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbljadwal.getModel();
        tfid.setText(model.getValueAt(tbljadwal.getSelectedRow(), 0).toString());
        tfprodi.setText(model.getValueAt(tbljadwal.getSelectedRow(), 1).toString());
        tfmatkul.setText(model.getValueAt(tbljadwal.getSelectedRow(), 2).toString());
        cmbhari.setSelectedItem(model.getValueAt(tbljadwal.getSelectedRow(), 3).toString());
        tfjam.setText(model.getValueAt(tbljadwal.getSelectedRow(), 4).toString());
        tfkodelab.setText(model.getValueAt(tbljadwal.getSelectedRow(), 5).toString());

    }//GEN-LAST:event_tbljadwalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menuJadwal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbhari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLidjadwal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlhari;
    private javax.swing.JLabel jljam;
    private javax.swing.JLabel jlkodealab;
    private javax.swing.JLabel jlmatkul;
    private javax.swing.JLabel jlprodi;
    private javax.swing.JTable tbljadwal;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfjam;
    private javax.swing.JTextField tfkodelab;
    private javax.swing.JTextField tfmatkul;
    private javax.swing.JTextField tfpesan;
    private javax.swing.JTextField tfprodi;
    // End of variables declaration//GEN-END:variables

    
}
